# Generated by Django 6.1 on 2026-09-14 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de zona',
                'verbose_name_plural': 'Estados de zona',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de zona',
                'verbose_name_plural': 'Tipos de zona',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='zonas.organizacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ecoenergy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('limite_kwh', models.DecimalField(decimal_places=2, help_text='Límite de consumo energético permitido para la zona.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='zonas.estadozona')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='zonas.organizacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='zonas.tipozona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['organizacion__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, help_text='Consumo energético del dispositivo en kWh.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='zonas.categoria')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='zonas.zona')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['zona__nombre', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('organizacion', 'nombre'), name='uq_zona_organizacion_nombre'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(fields=('zona', 'nombre'), name='uq_dispositivo_zona_nombre'),
        ),
    ]
