# Generated by Django 6.1 on 2026-09-28 12:31

import django.core.validators
import django.db.models.deletion
import monitoring.models
import monitoring.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertSeverity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1 = más leve, 5 = más grave.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="nivel",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Use un color hexadecimal, ej: #dc3545.",
                            )
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "severidad de alerta",
                "verbose_name_plural": "severidades de alerta",
                "db_table": "alert_severity",
                "ordering": ["level"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_alert_severity_name_alive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("level",),
                        name="uq_alert_severity_level_alive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "db_table": "category",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_category_name_alive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9-]{4,40}$",
                                "Solo mayúsculas, números y guiones (4 a 40 caracteres).",
                            )
                        ],
                        verbose_name="número de serie",
                    ),
                ),
                (
                    "nominal_consumption_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Consumo energético nominal del dispositivo en kWh (0,01 a 5.000).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("5000")),
                        ],
                        verbose_name="consumo nominal (kWh)",
                    ),
                ),
                ("installed_on", models.DateField(verbose_name="fecha de instalación")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="JPG, PNG o WEBP. Máximo 2 MB.",
                        upload_to=monitoring.models.device_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            monitoring.validators.validate_image_size,
                            monitoring.validators.validate_image_content,
                        ],
                        verbose_name="imagen",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="monitoring.category",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "dispositivo",
                "verbose_name_plural": "dispositivos",
                "db_table": "device",
                "ordering": ["zone__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConsumptionReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                (
                    "reading_at",
                    models.DateTimeField(verbose_name="fecha y hora de lectura"),
                ),
                (
                    "consumption_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10000")),
                        ],
                        verbose_name="consumo (kWh)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observaciones"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="monitoring.device",
                        verbose_name="dispositivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "lectura de consumo",
                "verbose_name_plural": "lecturas de consumo",
                "db_table": "consumption_reading",
                "ordering": ["-reading_at"],
                "permissions": [
                    ("export_consumptionreading", "Puede exportar lecturas a Excel")
                ],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="país"),
                ),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "fabricante",
                "verbose_name_plural": "fabricantes",
                "db_table": "manufacturer",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_manufacturer_name_alive",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="monitoring.manufacturer",
                verbose_name="fabricante",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                ("tax_id", models.CharField(max_length=12, verbose_name="RUT")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
                "db_table": "organization",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tax_id",),
                        name="uq_organization_tax_id_alive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "consumption_limit_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Límite de consumo energético permitido para la zona.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="límite de consumo (kWh)",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="monitoring.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "zona",
                "verbose_name_plural": "zonas",
                "db_table": "zone",
                "ordering": ["organization__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="monitoring.zone",
                verbose_name="zona",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("in_progress", "En revisión"),
                            ("resolved", "Resuelta"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("detected_at", models.DateTimeField(verbose_name="detectada el")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resuelta el"
                    ),
                ),
                (
                    "severity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="monitoring.alertseverity",
                        verbose_name="severidad",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="monitoring.consumptionreading",
                        verbose_name="lectura que la originó",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="monitoring.device",
                        verbose_name="dispositivo",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="monitoring.zone",
                        verbose_name="zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "alerta",
                "verbose_name_plural": "alertas",
                "db_table": "alert",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="ZoneStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "estado de zona",
                "verbose_name_plural": "estados de zona",
                "db_table": "zone_status",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_zone_status_name_alive",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="zone",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="monitoring.zonestatus",
                verbose_name="estado",
            ),
        ),
        migrations.CreateModel(
            name="ZoneType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "tipo de zona",
                "verbose_name_plural": "tipos de zona",
                "db_table": "zone_type",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_zone_type_name_alive",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="zone",
            name="zone_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="monitoring.zonetype",
                verbose_name="tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="consumptionreading",
            index=models.Index(
                fields=["device", "reading_at"], name="consumption_device__ef6087_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="consumptionreading",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("device", "reading_at"),
                name="uq_reading_device_datetime_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("zone", "name"),
                name="uq_device_zone_name_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("serial_number",),
                name="uq_device_serial_number_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "name"),
                name="uq_zone_organization_name_alive",
            ),
        ),
    ]
